### ISSUE TITLE
listbox is missing

### ISSUE THREAD

**Issue by 60-hz** [pd-l2ork/pd-l2ork#24] opened 2023-11-18 21:37 UTC
The listbox is part of basic ui of puredata and pd-l2ork is missing it.

I guess this is because pd-l2ork is based on a old version of pd...

**Comment by pd-l2ork** [comment] 2023-11-19 22:05
Yes, this is already on a TODO list. I am working as fast as I can addressing the remaining issues existing issues and will address catching up with latest pd shortly thereafter. Please note this is also a duplicate of #8 , so I will close this one.

**Closed by pd-l2ork** 2023-11-19 22:05 UTC
