### ISSUE TITLE
Does not compile on MacOS Apple Silicon M1  (arm64)

### ISSUE THREAD

**Issue by aourednik** [pd-l2ork/pd-l2ork#6] opened 2021-12-06 22:28 UTC
Followed all compilation instructions for Mac up to "5. Build the OSX app and the installer disk image (.dmg file) (15 minutes)
`make`

Got  acouple of these warnings:

```
warning: unknown warning option '-Wno-cast-function-type'; did you mean '-Wno-bad-function-cast'? [-Wunknown-warning-option]
...
d_soundfile.c:1699:33: warning: incompatible pointer types passing 'char (*)[1024]' to parameter of type 'char *' [-Wincompatible-pointer-types]
        soundfiler_readascii(x, &filename, ac, garrays, vecs, resize,
...
d_soundfile.c:1703:49: warning: incompatible pointer types passing 'char (*)[1024]' to parameter of type 'const char *' [-Wincompatible-pointer-types]
    fd = open_soundfile_via_canvas(x->x_canvas, &filename, &info, skipframes);
...
d_soundfile.c:1714:36: warning: incompatible pointer types passing 'char (*)[1024]' to parameter of type 'const char *' [-Wincompatible-pointer-types]
    if (file_is_a_flag_name(gensym(&filename), &nodash))

```

And these errors:
```
cc -mmacosx-version-min=10.9 -DPD  -Wall -W -Wstrict-prototypes -Wno-unused-parameter -Wno-parentheses -Wno-switch -Wno-cast-function-type -DHAVE_LIBDL -DMACOSX -DHAVE_UNISTD_H -I/usr/X11R6/include         -I../portaudio/include -I../portaudio/src/common         -I../portaudio/src/os/mac_osx/         -I../portmidi/pm_common -I../portmidi/pm_mac         -I../portmidi/porttime         -DUSEAPI_PORTAUDIO -DPA19 -DPA_USE_COREAUDIO -DNEWBUFFER -DMACOSX3 -DPA_BIG_ENDIAN -Wno-error -O2 -fast -fPIC -ftree-vectorize -mcpu=7450 -mtune=7450 -DINSTALL_PREFIX=\"\"  -c -o ../obj/g_canvas.o g_canvas.c 
clang: error: the clang compiler does not support '-mcpu=7450'
make[3]: *** [g_canvas.o] Error 1
make[2]: [pd] Error 2 (ignored)
/Library/Developer/CommandLineTools/usr/bin/make -C /Users/currentuser/Downloads/pd-l2ork/pd/src BUILDLAYOUT_DIR=/Users/currentuser/Downloads/pd-l2ork/packages cvs_root_dir=/Users/currentuser/Downloads/pd-l2ork DESTDIR=/Users/currentuser/Downloads/pd-l2ork/packages/darwin_app/build/Pd-L2Ork.app/Contents/Resources/app.nw prefix= libpddir= OPT_CFLAGS="-fast -fPIC -ftree-vectorize -mcpu=7450 -mtune=7450" UNAME=Darwin  install
cc -mmacosx-version-min=10.9 -DPD  -Wall -W -Wstrict-prototypes -Wno-unused-parameter -Wno-parentheses -Wno-switch -Wno-cast-function-type -DHAVE_LIBDL -DMACOSX -DHAVE_UNISTD_H -I/usr/X11R6/include         -I../portaudio/include -I../portaudio/src/common         -I../portaudio/src/os/mac_osx/         -I../portmidi/pm_common -I../portmidi/pm_mac         -I../portmidi/porttime         -DUSEAPI_PORTAUDIO -DPA19 -DPA_USE_COREAUDIO -DNEWBUFFER -DMACOSX3 -DPA_BIG_ENDIAN -Wno-error -O2 -fast -fPIC -ftree-vectorize -mcpu=7450 -mtune=7450 -DINSTALL_PREFIX=\"\"  -c -o ../obj/g_canvas.o g_canvas.c 
clang: error: the clang compiler does not support '-mcpu=7450'
make[3]: *** [g_canvas.o] Error 1
make[2]: *** [pd_install] Error 2
make[1]: *** [darwin_app_core] Error 2
copying pd-l2ork-specific externals...
done with l2ork addons.
mv: rename packages/darwin_app/Pd*.dmg to ./Pd*.dmg: No such file or directory
./tar_em_up.sh: 456: command failed with exit code 1, exiting now.
./tar_em_up.sh: 456: mv packages/darwin_app/Pd*.dmg .
make: *** [all] Error 1
```

**Comment by pd-l2ork** [comment] 2021-12-07 05:58
Thanks for the report. Until I get my hands on an arm CPU OSX machine I am not sure if I will be able to resolve this. Lemme see if I can identify one on campus... In the meantime, does the Intel-based DMG work through emulation?

**Comment by aourednik** [comment] 2021-12-13 09:25
@pd-l2ork Yes, the DMG sound input-output works through Rosetta emulation, but not video. GEM video (gemhead nodes etc.) does not launch.

**Comment by pd-l2ork** [comment] 2021-12-13 20:47
Thanks. I think Gem is broken as-is. I've managed to package it for OSX
only as a software-only 3D library (no GPU acceleration). This may be an
upstream issue.

Best,

Ico

-- 
Ivica Ico Bukvic, D.M.A.
Director, Creativity + Innovation
Institute for Creativity, Arts, and Technology

Virginia Tech
Creative Technologies in Music
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
***@***.***

ci.icat.vt.edu
l2ork.icat.vt.edu
ico.bukvic.net

**Comment by pd-l2ork** [comment] 2022-10-15 17:30
There have been some updates to Gem in the latest version that should allow for accelerated 3D graphics in Gem on OSX. Please let me know if this fixes it for you.

**Comment by 60-hz** [comment] 2022-10-15 20:29
I see that in pd-l2ork Version 2.16.0 (20221011-rev.ef920c98) Gem use [gemsdl2window].
Now, [gemglfw3window] is the new default window manager under OSX, and it support antialiasing. It was recently fixed so the buffer is correct with new M1 and retina screen.

**Comment by pd-l2ork** [comment] 2022-10-16 03:45
Right, but does it work at all and/or accelerated for you as it currently is? I am not the developer of Gem and honestly do not have the bandwidth to try to retrofit it to work with gemglfw3window. The fact that it is now accelerated is already a major step in the right direction.

**Comment by 60-hz** [comment] 2022-10-16 10:09
As a simple test with pd-l2ork, I replaced the old Gem folder from puredata Deken to pd-l2ork and surprisely, it worked.
[Here](https://github.com/umlaeute/Gem/issues/243) is the last buffer issue that IOhannes fixed recently for M1.
I recompiled and tested on my M1 computer and confirm that it worked so In think we have now a working Gem for new Apple computer.

**Comment by 60-hz** [comment] 2022-10-24 17:27
@pd-l2ork Thanks for the notification.
I tried:
Pd-L2Ork version 2.x (updated 2022-10-20)
File: Pd-L2Ork-2.16.0-20221019-rev.493d7d23-x86_64.dmg

Unfortunately, on my M1 Monterey computer, the software freeze after launch and console print without errors, I need to kill the process. Reseting preferences / erasing ~/pd-l2ork  folder didn't help.

Also, I checked the app architecture and I see no Gem binaries or even Gem folder inside... maybe something is wrong?

**Comment by pd-l2ork** [comment] 2022-10-25 00:09
Thanks for catching that. Somehow I managed to upload a broken build. I just uploaded a new one built today (version 20221024). Would you please try that one and report back? Thanks.

**Comment by 60-hz** [comment] 2022-10-25 07:47
This version works, thanks.
But I noticed that Gem is still using [gemsdl2window] as default window manager like `before.`
Also, pd-l2ork randomly crash sometimes at start here.

GEM: Graphics Environment for Multimedia
verbose( -1):GEM: ver: 0.94.git v0.94-275-g4bdb95d3
verbose( -1):GEM: compiled  on Oct 24 2022
verbose( -1):GEM: maintained by IOhannes m zmoelnig
verbose( -1):GEM: Authors :	Mark Danks (original version)
verbose( -1):GEM:		Chris Clepper
verbose( -1):GEM:		Cyrille Henry
verbose( -1):GEM:		IOhannes m zmoelnig
verbose( -1):GEM: with help by Guenter Geiger, Daniel Heckenberg, James Tittle, Hans-Christoph Steiner, et al.
verbose( -1):GEM: found a bug? miss a feature? please report it:
verbose( -1):GEM: 	homepage https://gem.iem.at/
verbose( -1):GEM: 	bug-tracker https://bugs.gem.iem.at/
verbose( -1):GEM: 	mailing-list https://lists.puredata.info/listinfo/gem-dev/
verbose( -1):GEM: compiled for MMX/SSE2 architecture
verbose( -1):GEM: using SSE2 optimization
verbose( -1):GEM: detected 8 CPUs
GEM: image loading plugins: SGI STB imageIO jpeg tiff
GEM: film loading plugins: AVF quicktime4linux
GEM: image saving plugins: SGI STB imageIO jpeg tiff
GEM: model loading plugins: OBJ
GEM: video record plugins: QT4L
GEM: video capture plugins: AVF decklink

**Comment by pd-l2ork** [comment] 2022-10-31 14:05
The Gem included is directly from the repository you shared, so I am unsure what is causing this issue to be honest. Does Gem on Pd use gemglfw3window by default? If so, where would I see this?

**Comment by 60-hz** [comment] 2022-10-31 14:52
You need to configure Gem to use  gemglfw3window as default on apple.
https://github.com/umlaeute/Gem/wiki/How-to-build-Gem-on-macOS-Sierra-%2810.12%29

I see no gemglfw3window binaries in the Gem package inside this last pd-l2ork release.

**Comment by pd-l2ork** [comment] 2022-10-31 15:03
I see. I just added a commit that hopefully fixes this and am making a new OSX build. Does anyone know if Windows can also benefit from having glfw3 and/or if it can be even built on Windows?

**Comment by pd-l2ork** [comment] 2022-10-31 16:21
OK, I just re-tested the new build and it now uses gemglfw3window by default. Please download and test. As for instability, this pertains to the nw.js and I am still looking for: 1) the cause, and 2) the most stable version that is also not super slow. Looks like anything newer than 0.42.3 is more than 10 times slower in rendering which I find unacceptable. Hope this helps. I will close this unless I hear otherwise from one of you.

**Comment by 60-hz** [comment] 2022-10-31 23:34
Gem is now working well with gemglfw3window thanks.
Yes, the nw.js instability is making pd-l2ork quit almost one time out of 3 here, often at launch... I hope something will allow a longer experience in the future!

**Comment by pd-l2ork** [comment] 2022-11-04 01:58
@60-hz I just uploaded a newer version of pd-l2ork for OSX that fixes one bug that may be responsible for the instabilities you experienced. You can download it from the L2Ork's website, as usual. Would you please test and report if it is any more stable? Also, please indicate your version of OSX. Thanks!

**Comment by 60-hz** [comment] 2022-11-06 11:36
I tried with the last build, under macOS monterey (12.6) , I deleted the file org.puredata.pd-l2ork.plist in preferences before.
I encountered far less crashes than before, but still a few random at times.

Here is a terminal report of a crash loading pd-l2ork with -verbose -stderr :

verbose(3): lua 0.6~svn (GPL) 2008 Claude Heiland-Allen <claude@mathr.co.uk>
verbose(3): pdlua: compiled for pd-0.48 on Nov  3 2022 21:30:01
verbose(3): Using lua version 5.4
pdlua: using JavaScript interface (Pd-l2ork nw.js version)
Received signal 11 SEGV_MAPERR 000000000000
 [0x000115da1e2c]
 [0x000115da1d21]
 [0x7ff81a2e2dfd]
 [0x000000000000]
 [0x00030dd73b30]
[end of stack trace]
pd: exiting

Also, I see this in terminal when closing a new window:
[32530:259:1106/115457.140869:ERROR:gles2_cmd_decoder.cc(18162)] [.RenderWorker-0x7fd123857000.GpuRasterization]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[32530:259:1106/115457.141881:ERROR:gles2_cmd_decoder.cc(18162)] [.RenderWorker-0x7fd123857000.GpuRasterization]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name

when using menu -> open:
2022-11-06 11:56:13.309 nwjs[32525:9586414] dyn.age81a2py is not a valid allowedFileType because it doesn't conform to UTTypeItem
2022-11-06 11:56:13.309 nwjs[32525:9586414] dyn.age8048dc is not a valid allowedFileType because it doesn't conform to UTTypeItem
2022-11-06 11:56:13.309 nwjs[32525:9586414] dyn.age8048dy is not a valid allowedFileType because it doesn't conform to UTTypeItem
2022-11-06 11:56:13.309 nwjs[32525:9586414] dyn.age80u3pqsa is not a valid allowedFileType because it doesn't conform to UTTypeItem

**Comment by pd-l2ork** [comment] 2022-11-06 19:34
Thanks for the update @60-hz . The segfault you are seeing is likely related to the following nw.js bug that appears to have been fixed in 0.60.1 (pd-l2ork is currently running 0.28.3 because newer versions have other issues): https://github.com/nwjs/nw.js/issues/7828

The other warnings/errors should not be causing crashes and both appear related to nw.js.

**Comment by pd-l2ork** [comment] 2022-11-07 01:29
@60-hz would you please try these two versions and report if either of them fixes your issues?

https://l2ork.music.vt.edu/data/pd-l2ork/Pd-L2Ork-2.16.0-20221106-rev.f126e367-x86_64.dmg (uses nw.js 0.42.3, last one that does not have slowdown issues)

https://l2ork.music.vt.edu/data/pd-l2ork/Pd-L2Ork-2.16.0-20221106-rev.47ae6907-x86_64.dmg (uses latest nw.js 0.70.1 and suffers from a significantly slower loading of patches, see L2Ork-Tweeter which can take up to 10 seconds to load on a relatively recent laptop, when on 0.42.3 it loads within a second)

**Comment by pd-l2ork** [comment] 2022-11-08 03:42
@60-hz actually, I think I finally found the reason for the slowdown and now we can use newer nw.js. Below is a link to the latest build (there may be some cosmetic regressions that I will investigate further). Please test and see if this is any more stable:

https://l2ork.music.vt.edu/data/pd-l2ork/Pd-L2Ork-2.16.0-20221107-rev.290fffc1-x86_64.dmg

**Comment by 60-hz** [comment] 2022-11-08 08:48
@pd-l2ork great, Great, I tried different patches and encounter no crash at all yet.

But I found a bug: when closing a patch, the window disappear without asking to save, and the program remain persistent (a sound can still be heard from dac~ / a gem window stay visible...).

**Comment by pd-l2ork** [comment] 2022-11-08 13:07
Great. Yes, these little regressions will happen given the new version of nw.js. Please keep reporting them on this thread, so that I can track them down. Thanks.

**Comment by pd-l2ork** [comment] 2022-11-08 17:44
> But I found a bug: when closing a patch, the window disappear without asking to save, and the program remain persistent (a sound can still be heard from dac~ / a gem window stay visible...).

Can you consistently reproduce this? I was unable to make this happen on my computer. Perhaps there is an object that may be causing problems. If so, can you send me the patch that caused this to happen? Thanks.

**Comment by 60-hz** [comment] 2022-11-08 19:08
It behaves the same all the time on my computer... (macOS monterey 12.6).
I simply open the Test audio and midi and I have the same problem: when I close, the patch window is not visible anymore but the sound continue and if I open another one I have the error message "warning: tone-osc: multiply defined
warning: tone-mon: multiply defined" for instance.

**Comment by pd-l2ork** [comment] 2022-11-08 23:35
@60-hz OK, I just figured it out. Another nwjs bug is causing this, see:

https://github.com/nwjs/nw.js/issues/7981

Looks like we will need to stick with nwjs 0.67.1. Below is a build with nwjs 0.67.1. Please test and report:

https://l2ork.music.vt.edu/data/pd-l2ork/Pd-L2Ork-2.16.0-20221107-rev.0c497f21-nw0.67.1-x86_64.dmg

**Comment by 60-hz** [comment] 2022-11-10 15:21
Woops, the link is broken...

**Comment by pd-l2ork** [comment] 2022-11-10 15:48
@60-hz oops, just edited the link. this one has even more updates...

**Comment by 60-hz** [comment] 2022-11-10 16:11
Great, working well so far!
What I discovered with nwjs 0.70 is that the zoom feature is centered to the mouse cursor and not the upper left part of the patch, which is great. But that's nice to see stability here!

**Closed** 2022-11-10 19:48 UTC
